name: NUSH
version: 0.0.1.0
github: "terkwood/NUSH"
license: MIT
author: "Terkwood"
copyright: "2021 Terkwood"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/terkwood/NUSH#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  NUSH-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - NUSH

tests:
  NUSH-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - NUSH
